### ISSUE TITLE
From_Corners Materials bug

### ISSUE THREAD

**Issue by benalexanderbonza** [LCAV/pyroomacoustics#381] opened 2024-11-21 10:32 UTC
There seems to be an issue with using different material frequency-band coefficients for walls/ceiling/floors.

I get this error: "Error: All walls should have the same number of frequency bands"

When I use the same materials on shoebox rooms, it works, and if I just use different flat coefficients on the walls/ceiling/floor on the from_corners, it works.

(It also seems that if I use a sim_order larger than 3-4 on from_corners it doesn't run and my python environment stops responding - I don't know whether I'm using up all available memory? or whether this is linked to the previous bug)

**Comment by fakufaku** [comment] 2024-12-07 11:09
Thanks for reporting. I will investigate.

**Comment by fakufaku** [comment] 2024-12-07 11:14
> (It also seems that if I use a sim_order larger than 3-4 on from_corners it doesn't run and my python environment stops responding - I don't know whether I'm using up all available memory? or whether this is linked to the previous bug)

This is probably a limitation of the software. The image source model has exponential complexity for general rooms.
Moving to hybrid simulation by using ISM with max_order = 2 or 3 and using ray tracing for the rest may solve your problems.

**Comment by fakufaku** [comment] 2024-12-07 15:25
@benalexanderbonza I'd like to try to fix this bug. Could you please share a code snippet that illustrates what works with Shoebox, but fails with from_corners?

Thanks!

**Comment by fakufaku** [comment] 2024-12-07 15:30
BTW, are you by any chance using the combination of `from_corners` and `extrude` to make a 3D room?

In that case, I may know what the problem is.

**Comment by fakufaku** [comment] 2024-12-07 16:49
I could reproduce the issue. The problem is that extrude did not properly extend the number of bands of the materials to match that of the existing walls.

A fix is underway in PR #388 .

**Closed** 2024-12-08 13:54 UTC
Labels: bug

**Comment by fakufaku** [comment] 2024-12-08 14:38
The fix has been pushed to v0.8.3 if you'd like to give it a go.

**Comment by benalexanderbonza** [comment] 2024-12-09 08:09
That's great, thank you! All seems to be working with multiple bands now! Will try and implement a hybrid model with ray tracing too!

**Comment by benalexanderbonza** [comment] 2024-12-09 08:30
Unfortunately, I don't know if the hybrid model will work for my simulations as I'm modelling a spatial microphone so the diameter of the ray tracing receiver will have to be quite small, and therefore the number of rays would make the simulations very slow. Thank you for all your help!
